trigger: none

pool: 
  vmImage: 'ubuntu-latest'
  
steps:

  - task: DownloadSecureFile@1
    displayName: Download secure file kubeconfig_k3s
    name: kubeconfig_k3s
    inputs:
      secureFile: 'kubeconfig_k3s.yml'
  - bash: echo "Antes de comenzar"
  - bash: mkdir ~/.kube
  - bash: echo "$(kubeconfig_k3s.secureFilePath)"
  - bash: env
  - bash: cat $KUBECONFIG_K3S_SECUREFILEPATH >  ~/.kube/config
  - bash: kubectl cluster-info
  - bash: kubectl get po --all-namespaces